name: Plugin Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Get current version
        id: get_version
        run: |
          version=$(grep -oP 'Version:\s*\K[0-9.]+' snn-tickets.php)
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Bump version if release
        if: contains(github.event.head_commit.message, 'release')
        run: |
          current_version=$(grep -oP 'Version:\s*\K[0-9.]+' snn-tickets.php)
          next_version=$(awk -F. '{print $1 "." ($2+1)}' <<< "$current_version")
          sed -i "s/Version: $current_version/Version: $next_version/" snn-tickets.php
          echo "new_version=$next_version" >> $GITHUB_ENV

      - name: Create zip file
        run: |
          zip -r snn-tickets.zip . -x '*.git*' '*.github*'

      - name: Create GitHub Release
        if: contains(github.event.head_commit.message, 'release')
        uses: softprops/action-gh-release@v1
        with:
          files: snn-tickets.zip
          tag_name: "v${{ env.new_version }}"
          release_name: "Release v${{ env.new_version }}"
          body: "Release v${{ env.new_version }} of the plugin."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Pre-release
        if: contains(github.event.head_commit.message, 'alphatag')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: snn-tickets.zip
          tag_name: "pre-v${{ env.version }}"
          release_name: "Pre-release v${{ env.version }}"
          body: "Pre-release v${{ env.version }} of the plugin."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
